---
title: "Stepper Sequencer"
output:
  rmdformats::readthedown:
    highlight: kate
word_document: default
date: '`r Sys.Date()`'    
---


```{r knitr_init, echo=FALSE, cache=FALSE}
library(knitr)
library(rmdformats)

## Global options
options(max.print="75")
opts_chunk$set(echo=FALSE,
	             cache=TRUE,
               prompt=FALSE,
               tidy=FALSE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)
```


## Setup: Load Libs and Functions

```{r load_libs, echo = TRUE}
# load libraries
library(RSelenium)
library(rvest)
library(tidyverse)
```


```{r load_func}
# load function
source("stepperSeq.R") 
```


## Input Data and Make Indices

```{r initialise, echo = TRUE}
# load names and data
input_seq <- read_csv("input/input.seq.txt",col_names = FALSE)

# make indices
single <- seq(1:nrow(input_seq)) # using indices instead of direct ref to df

# start Selenium via terminal before this step
#docker run -d -p 4445:4444 selenium/standalone-firefox:3.0.1
```

## Establish Remote Connection

```{r connect}
# make connection
remDr <-remoteDriver(remoteServerAddr = "localhost" 
                     , port = 4445L
                     , browserName = "firefox")
# initialise
remDr$open()
```

## Process Data

```{r download-dat, echo = TRUE}

# NOTE: Remove any text files in the current working directory...prior to new run.

# download files 
multi.seq <-plyr::alply(single,1,stepFunction,df=input_seq) # returns an empty list :: OK
```

## Text Processing



```{bash fnAppend, echo = TRUE}
# add filenames to each line
for f in *.txt;
do sed -i -e '1,$s/$/'"\,$f"'/' $f;
done
```

```{bash join-dat, echo = TRUE}
# join files together
cat *.txt > output/filenames-appended.txt
```

```{bash format-dat, echo = TRUE}
# merge every 2 lines --> more appropriate wide format
awk '{ ORS = (NR%2 ? "," : RS) } 1' output/filenames-appended.txt > output/outputDF.txt
```

## Read in Output File
```{r read-outputs, include = TRUE}
output_seq <- read_csv("output/outputDF.txt",col_names = FALSE)
```

## Session Info
```{r sessinfo, include = TRUE}
sessionInfo()
```

